$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: opal-sd-placement-dev
model: azureml:noop-model:1
code_configuration:
  code: ./noop-model
  scoring_script: score.py
environment:
  conda_file: ./noop-model/conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS2_v2
instance_count: 1
request_settings:
  request_timeout_ms: 180000
  max_concurrent_requests_per_instance: 4
liveness_probe:
  initial_delay: 30
  timeout: 10
  period: 10
readiness_probe:
  initial_delay: 30
  timeout: 10
  period: 10
