$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: opal-sd-placement-dev
model: azureml:noop-model:1
environment:
  image: ${ACR_LOGIN_SERVER}/opal/aml-sd-stub:${IMAGE_TAG}
instance_type: Standard_NC6s_v3
instance_count: 1
request_settings:
  request_timeout_ms: 180000
  max_concurrent_requests_per_instance: 1
liveness_probe:
  initial_delay: 60
  timeout: 10
  period: 10
readiness_probe:
  initial_delay: 60
  timeout: 10
  period: 10
